Changes 1
radhika011/parking-lot-api-springboot pull request #1
Opened 2021-05-09 08:53 UTC by radhika011

Changes made :-

In Principal Controller.java -
1) Use RESTful naming conventions for URLs  
2) Use @PathVariable annotation instead of @RequestParam annotation 
3) Use @Autowired to use the Bean 
4) Removing unnecessary imports

In AppConfig.java -
1) Add AppConfig.java file to define a Bean

In DemoApplication.java
1) Removing @RestController annotation
2) Removing unnecessary imports

2021-05-22 17:28 UTC, techswappy commented on AppConfig.java
> +	@Bean(initMethod = "init")
@Bean is helpful when you have don't have access to class or you want to create lot of custom beans of the same class using different parameters. If you are using the default option - simply annotating the class with @Service / @Component will allow spring to automatically do this for you.

2021-05-22 17:32 UTC, techswappy requested changes
Given a few more pointers and feedback about how we can improve the code here. I want you to now check out spring boot data package and see how we can integrate MongoDB with this?

2021-05-22 17:32 UTC, techswappy commented on PrincipalController.java
> +	ParkingLot pl1;
let's name our variable a little better - it makes the code more readable - change `pl1` to `parkingLot`

2021-05-22 17:32 UTC, techswappy commented on PrincipalController.java
> +		Car car1 = new Car(car_id);
same here `car1` to `car`

2021-05-22 17:32 UTC, techswappy commented on PrincipalController.java
> +		return  "Car "+car_id+" parked at "+slotNo;
read about StringBuilder class that Java 8 provides and how you can use it here

2021-05-22 17:32 UTC, techswappy commented on PrincipalController.java
> +	@RequestMapping(value="/parking-lot/slot/slot-no/{slot_no}/unpark")
I prefer camel case for url definitions as we can avoid usage of special characters `-` -> `parking-lot` to `parkingLot`

2021-05-22 17:32 UTC, techswappy commented on PrincipalController.java
> +		return "Car with car ID "+unparked.getCarID()+" unparked from "+slot_no;
string builder

2021-05-23 18:01 UTC, radhika011 commented
In PrincipalController.java -
1) Changing variable names - pl1 to parkingLot and car1 to car
2) Using StringBuilder to optimize string append operations
3) Using camelCase in URLs and other variables

Deleting AppConfig.java

In ParkingLot.java
1) Adding @Service annotation

2021-05-23 18:39 UTC, techswappy approved these changes

2021-05-23 18:40 UTC, merged